[package]
name = "img-colors"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kmeans = "0.1.0"
rand = "0.7.3"
image = "0.23.8"
